name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Dockerhub
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
        continue-on-error: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you need

      - name: Install Node.js dependencies
        run: npm install # Assuming your Node.js project has a package.json file

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/client-end:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/client-end:latest
